
#List of entity configurations
[[entities]]
	entity = "minecraft:creeper"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "minecraft:silverfish"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "minecraft:endermite"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "greekfantasy:hydra_head"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "majruszs_difficulty:creeperling"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "minecraft:vex"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "minecraft:slime"
	minTier = 0
	maxTier = 2
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "minecraft:magma_cube"
	minTier = 0
	maxTier = 2
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
[[entities]]
	entity = "stalwart_dungeons:nether_wart_cocoon"
	minTier = 0
	maxTier = 0
	presetAffixes = []
	affixList = []
	affixPermission = "BLACKLIST"
